---
title: "Melbourne CogSci22 Meetup"
output: html_document
---

<style type="text/css">

.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>


<div class="row" style="padding-top: 40px;">
<div class="col-sm-12">

Cognitive Scientists around the world are organizing [local meetup groups]( 
https://cognitivesciencesociety.org/cogsci-2022-meetups/)
in conjunction with  [CogSci 2022](  https://cognitivesciencesociety.org/cogsci-2022/ ). A meetup in Melbourne is planned for the afternoon of July 27. Please come by and hang out with others who are interested in Cognitive Science. 

* *What*: A 2-hour workshop for cognitive scientists.

* *Who*: Anyone with an interest in Cognitive Science is welcome to attend, and registering for CogSci 2022 is not required. Students at all levels (e.g.\ undergraduates, honours students, and PhD students) and early career researchers are especially welcome and are encouraged to present their work. Industry researchers are also welcome.

* *When*: July 27, 2:00 pm - 4:00 pm (Melbourne time) 

* *Where*: University of Melbourne, [Yasuko Hiraoka Myer Room](
https://maps.unimelb.edu.au/parkville/building/158/yasuko-hiraoka-myer-room
)

* *Format*: Our goal is to use much of the time for discussion and personal interaction. The format has not yet been finalized, but the first part of the workshop will focus on small group discussions. Each attendee will have a chance to introduce themselves to their group and talk about their interests. The second part will focus on research presentations. There will be two kinds of presentations:
    * 2 minute flash talks are for people who'd like to give a brief introduction to something they're working on, and it's fine to sign up for a flash talk regardless of whether you have any results to share. 
    * 8 minute research talks are for people who'd like to present a project in a bit more detail. 
    
    If you have a recent submission to CogSci, MathPsych, the Australasian Brain and Psychological Sciences Meeting or another relevant conference we encourage you to present the same work at the meetup (as either a 2 minute talk or an 8 minute talk)


* *Registration*: Registration is free, but please fill out this [registration form]( https://docs.google.com/forms/d/e/1FAIpQLSfdwm1Sx2iDfqY1fzWmwZbE89nygGuQ03aKCNV3WKvk6jaGnA/viewform?usp=sf_link ) by the end of July 15. Late registration is possible but we'll finalize the schedule shortly after July 15. 

* *Code of Conduct*: The meetup code of conduct is [here]( codeofconduct.html ).

* *Organizers*: The meetup is organized by [Daniel Bennett]( https://bennett-daniel.github.io/ ) and [Charles Kemp]( http://www.charleskemp.com/ ). Please get in touch with either of us if you have ideas to share.

</div>
</div>
